service: bonjour-theodo

provider:
  name: aws
  runtime: nodejs8.10

  stage: dev
  region: eu-west-2

  environment:
    MONGO_USER: yulingc
    MONGO_PASSWORD: bonjourtheodo18
    MONGO_DB_NAME: bonjourtheodo
    MONGO_HOST: ds247061.mlab.com
    MONGO_PORT: 47061

functions:
  chatbot:
    handler: functions/chatbot/handler.chatbot
    environment:
      FB_APP_TOKEN: b43c9289-f3a7-4ce7-a9ab-b511e4ff5c94
      FB_PAGE_ACCESS_TOKEN: EAAHv9RkFk7QBAOBZAG1LPqIFGDcyyssHu1ZC3FKG7dPQeJfiko6H2XUTUuCX67BqywHqpCIjON6OqH9UHhzzI857gOqr1P21uqObTcGDdTMGnC2SUlroZC23vGXmz8iLdVJd1cmzOyb4o8pHLYw6hEjH53qMaWRH4vld59lXAZDZD
    events:
      - http:
          path: chatbot
          method: GET
          integration: lambda
      - http:
          path: chatbot
          method: POST
          integration: lambda
  teamManager:
    handler: functions/team/handler.teamManager
    event:
      - schedule: rate(7 days)
    environment:
      TRELLO_API_KEY: 85784fbaa1ea02a3177ec5a7a2ec8574
      TRELLO_API_TOKEN: 8cb3f786cb2e7cbe05b89207422b8c88903f0052c70b06aaea5a2d18fad770b3
      TRELLO_CONTACT_BOARD_ID: JLBMh7wp
      THEODO_LIST_ID: 586d6013f8b9fae261791916
